### ISSUE TITLE
Leading zero in address trimmed

### ISSUE THREAD

**Issue by Benyamin001** [drlecks/Simple-Web3-Php#35]
Hi
I call a contract method that return a list of addresses but address that start with 0x0 trimmed and get wrong
address that get from PHP 0x5b2ae867657564db1d783b73eaa68e202e933db
but the correct address is 0x05b2AE867657564dB1D783b73eaa68E202e933db

**Comment by drlecks** [comment]
Hi, the problem is related with this issue:
#33 

web3p/rlp is an external dependency and the version 3.5 seems buggy. They added a left-zero-trimming that breaks leading zero addresses.

As `rpl` is a sub dependency of `ethereum-offline-raw-tx`, I'm not sure that you can force using a valid version (3.4). One solution would be to manually to delete the if statement at `rlp/src/Types/Str.php:41`

```php
if (mb_strlen($input) > 2) {
      $input = ltrim($input, '0');
}
```

Note that this is a temporal/bad solution as `composer update` would wipe it out.
