### ISSUE TITLE
[Conflicts] Can't install via composer require

### ISSUE THREAD

**Issue by ndirpaya** [drlecks/Simple-Web3-Php#4]
Hello, 
I'm having issues installing this package. There seems to be a number of conflicts.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires drlecks/simple-web3-php ^0.9.0 -> satisfiable by drlecks/simple-web3-php[v0.9].
    - drlecks/simple-web3-php v0.9 requires kornrunner/ethereum-offline-raw-tx ^0.4.0 -> found kornrunner/ethereum-offline-raw-tx[0.4.0] but the package is fixed to 0.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by drlecks** [comment]
Hi!

>... found kornrunner/ethereum-offline-raw-tx[0.4.0] but the package is fixed to 0.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

This states that you have a previous composer requirement from "ethereum-offline-raw-tx" with version 0.2.4. and this package is locked on your composer.lock file. This may be due to a failed or old install, or you may be previously using "ethereum-offline-raw-tx" on your project with an older version.

If it's possible, change the version of "ethereum-offline-raw-tx" to 0.4.0 in your composer.json. Then run "composer update" and try to install again simple-web3-php.
